apiVersion: v1
kind: Pod
metadata:
  name: sleeping-pod 
  labels:
    app: sleeping-pod
spec:
  containers:
  - image: centos
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    imagePullPolicy: IfNotPresent
    name: sleeping-pod
  restartPolicy: Always
